py_binary(
  name = "ex_1",
  srcs = ["ex_1.py"],
  deps = ["//common"],
  python_version = "PY2",
)

py_binary(
  name = "ex_3",
  srcs = ["ex_3.py"],
  deps = ["//common"],
  python_version = "PY2",
)