py_binary(
  name = "ex_1",
  srcs = ["ex_1.py"],
  deps = ["//common"],
  python_version = "PY2",
)

py_binary(
  name = "ex_3",
  srcs = ["ex_3.py"],
  deps = ["//common"],
  python_version = "PY2",
)

py_binary(
  name = "ex_4",
  srcs = ["ex_4.py"],
  deps = ["//common"],
  python_version = "PY2",
)

py_binary(
  name = "ex_5",
  srcs = ["ex_5.py"],
  deps = ["//common"],
  python_version = "PY2",
)

py_binary(
  name = "ex_6",
  srcs = ["ex_6.py"],
  deps = ["//common"],
  python_version = "PY2",
)

py_binary(
  name = "ex_7",
  srcs = ["ex_7.py"],
  deps = ["//common"],
  python_version = "PY2",
)

py_binary(
  name = "ex_8",
  srcs = ["ex_8.py"],
  deps = ["//common"],
  python_version = "PY2",
)

py_binary(
  name = "ex_9",
  srcs = ["ex_9.py"],
  deps = ["//common"],
  python_version = "PY2",
)

py_binary(
  name = "ex_12",
  srcs = ["ex_12.py"],
  deps = ["//common"],
  python_version = "PY2",
)

py_binary(
  name = "ex_16",
  srcs = ["ex_16.py"],
  deps = ["//common"],
  python_version = "PY2",
)

py_binary(
  name = "ex_17",
  srcs = ["ex_17.py"],
  deps = ["//common"],
  python_version = "PY2",
)
